<?php

namespace erp\commercialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * devisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class devisRepository extends EntityRepository
{
}
